name: 'Build OpenGD77'
description: ' '
inputs:
  branch:  # id of input
    description: 'Branch to checkout'
    required: true
    default: 'CItesting'
  radio:
    description: 'Radio: GD77/GD77s/DM1801/RD5R'
    required: true
    default: 'GD77'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch }}
    - ${{ inputs.radio }}
